### PR TITLE
fix(typography): style `kbd` element

### PR DESCRIPTION
**Pull request by Kiarokh**
## Preview
of course this is not in the PR
image

### CODE REVIEW

**Comment by Kiarokh** [comment]
couldn't run lint @jgroth 
image

**Review by adrianschmidt — APPROVED** [review]

**Comment by jgroth** [comment]
That was fast! :smile:

**Comment by Kiarokh** [comment]
me <3 Kompendium 😄

**Comment by Kiarokh** [comment]
who will update Elements now :)?

**Pull request merged**
