### PR TITLE
fix(style): allow long `<code />` blocks to render in multi lines

### PR DESCRIPTION
**Pull request by Kiarokh**
To prevent broken UI and sideways scrolling in the page.

fix https://github.com/jgroth/kompendium/issues/112

### CODE REVIEW

**Comment by adrianschmidt** [comment]
I'll bring this down and have a look, but initially, I'm opposed. Code should not be soft-wrapped, as it decreases legibility significantly, because line breaks may have semantic meaning in code, as opposed to most instances in natural language.

**Comment by Kiarokh** [comment]
if people want indentation, wouldn't they just use `<pre`? Like code blocks… 
`<code` is usually a small piece of text. But sometimes it seems it can be big too, as shown in the issue.

**Review by adrianschmidt — APPROVED** [review]

**Comment by adrianschmidt** [comment]
I don't know why I felt I would still need to check this locally. Sorry for keeping you waiting! 🙇‍♂️

**Comment by Kiarokh** [comment]
thank you so much 🙏

**Pull request merged**
